# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=120, null=True)),
                ('code', models.CharField(max_length=4)),
                ('basis', models.CharField(max_length=120)),
                ('subbasis', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
