# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addoperator',
            name='pickupId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addoperator',
            name='pickupLocation',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='addoperator',
            name='pickupTime',
            field=models.TimeField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='addoperator',
            name='time',
            field=models.TimeField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='addoperator',
            name='basis',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addoperator',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addoperator',
            name='operator',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='addoperator',
            name='subbasis',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
